Svbase/Svbase/Controllers/BeneficiaryController.cs
using System.Threading.Tasks;
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    //Категорії
    public class BeneficiaryController : GeneralController
    {
        private readonly IBeneficiaryService _beneficiaryService;

        public BeneficiaryController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _beneficiaryService = ServiceManager.BeneficiaryService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public async Task<ActionResult> List()
        {
            var beneficiaries = await _beneficiaryService.GetAllBeneficiariesAsync();

            return View(beneficiaries);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(BeneficiaryCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List");
            }

            var newItem = model.Update(new Beneficiary());
            _beneficiaryService.Add(newItem);
            if (Request.IsAjaxRequest())
            {
                return Json(new
                {
                    status = "success"
                });
            }
            return RedirectToAction("List");
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(BeneficiaryCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var beneficiary = _beneficiaryService.FindById(model.Id);
            if (beneficiary == null)
            {
                return Json(new { status = "error" });
            }
            beneficiary = model.Update(beneficiary);
            _beneficiaryService.Update(beneficiary);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _beneficiaryService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Views/Beneficiary/List.cshtml
@using Svbase.Core.Models
@model IEnumerable<BeneficiaryCreateModel>
<div class="container body-content">
    <div class="row page-header">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-8 col-xs-12">
                    <h2 style="margin-top: 0">Категорії</h2>
                </div>
                <div class="col-md-4 col-xs-12">
                    <a class="btn btn-primary pull-right"
                       data-toggle="modal"
                       data-target="#beneficiaryCreateModal">
                       Додати категорію
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th class="border-bottom-none">
                                    <span>Назва</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var beneficiary in Model)
                            {
                                <tr data-id="@beneficiary.Id">
                                    <td class="col-xs-12">
                                        <a>@beneficiary.Name</a>
                                        @if (beneficiary.CanDelete)
                                        {
                                            <i style="color: red; cursor: pointer"
                                               class="pull-right glyphicon glyphicon-trash"
                                               data-action="delete"
                                               data-item-id="@beneficiary.Id"></i>
                                        }
                                        <i style="color: gray; margin-right: 5px; cursor: pointer"
                                           class="pull-right glyphicon glyphicon-pencil"
                                           data-action="edit"
                                           data-item-id="@beneficiary.Id"></i>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_BeneficiaryCreate", new BeneficiaryCreateModel())
@Html.Partial("_BeneficiaryEdit")
@Html.Partial("_ConfirmDelete")

<script>
    $('[data-action="edit"]').click(function () {
        var item = $(this).parent().find("a")[0].text;
        var id = $(this).data('itemId');
        $('#EditName').val(item);
        $('#EditId').val(id);
        $('#itemEditModal').modal();
    });

    $('[data-action="delete"]').click(function () {
        var id = $(this).data('item-id');
        $('#confirmDeleteModal').modal('show');
        $('#confirmDeleteModal')
            .find("#submitDelete")
            .data("item-id", id);
    });

    $("#submitDelete").click(function () {
        var id = $(this).data('item-id');
        $.get('@Url.Action("Delete", "Beneficiary")', { id })
            {
                var item = $(".table-striped > tbody").find("[data-id=" + id + "]");
                 $(item).remove();
            };

        $('#confirmDeleteModal').modal('hide');

    });
</script>