Svbase/Svbase/Controllers/ApartmentController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class ApartmentController : GeneralController
    {
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public ApartmentController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(ApartmentCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City");//Todo page not found
            }

            var newApartmentItem = model.Update(new Apartment());
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            return RedirectToAction("Details", "Street", new { id = model.StreetId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var apartment = _apartmentService.GetById(id);
            if (apartment == null)
            {
                RedirectToAction("List", "City");
            }
            return View(apartment);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(ApartmentCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var apartment = _apartmentService.FindById(model.Id);
            if (apartment == null)
            {
                return Json(new { status = "error" });
            }
            apartment.Name = model.Name;
            _apartmentService.Update(apartment);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _apartmentService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Controllers/CityController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class CityController : GeneralController
    {
        private readonly ICityService _cityService;
        private readonly IStreetService _streetService;
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public CityController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _cityService = ServiceManager.CityService;
            _streetService = ServiceManager.StreetService;
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(CityCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List");
            }

            var newCityItem = model.Update(new City());
            var newStreetItem = new Street { Name = Consts.DefaultAddress, City = newCityItem };
            var newApartmentItem = new Apartment { Name = Consts.DefaultAddress, Street = newStreetItem };
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _cityService.Add(newCityItem);
            _streetService.Add(newStreetItem);
            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            if (Request.IsAjaxRequest())
            {
                return Json(new
                {
                    status = "success"
                });
            }
            return RedirectToAction("List");
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(CityCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var city = _cityService.FindById(model.Id);
            if (city == null)
            {
                return Json(new { status = "error" });
            }
            city = model.Update(city);
            _cityService.Update(city);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var city = _cityService.GetCityById(id);
            if (city == null)
            {
                RedirectToAction("List");
            }
            return View(city);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _cityService.DeleteById(id);

            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult List()
        {
            return View(_cityService.GetCities());
        }
    }
}

Svbase/Svbase/Controllers/StreetController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class StreetController : GeneralController
    {
        private readonly IStreetService _streetService;
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public StreetController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _streetService = ServiceManager.StreetService;
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(StreetCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City"); //Todo page not found
            }

            var newStreetItem = model.Update(new Street());
            var newApartmentItem = new Apartment { Name = Consts.DefaultAddress, Street = newStreetItem };
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _streetService.Add(newStreetItem);
            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            return RedirectToAction("Details", "City", new { id = model.CityId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(StreetCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var street = _streetService.FindById(model.Id);
            if (street == null)
            {
                return Json(new { status = "error" });
            }
            street.Name = model.Name;
            street.Pseudonym = model.Pseudonym;
            _streetService.Update(street);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var street = _streetService.GetStreetById(id);
            if (street == null)
            {
                RedirectToAction("List", "City");
            }
            return View(street);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _streetService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Views/Street/Details.cshtml
@using Svbase.Core.Consts
@using Svbase.Core.Models
@model StreetViewModel
<div class="container body-content margin-top">
    <div class="row page-header">
        <div class="col-sm-12 ignore-padding">
            <div class="col-md-6 col-xs-12">
                <h2 style="margin-top: 0">
                    <span>@Model.Name</span>
                    @if (!string.IsNullOrEmpty(@Model.Pseudonym))
                    {
                        <span>&nbsp;</span>
                        <span class="pseudonym-color">(@Model.Pseudonym)</span>
                    }
                </h2>
            </div>
            <div class="col-md-6 col-xs-12">
                <a href="@Url.Action("Details", "City", new {id = Model.CityId})" class="pull-right padding-top-10">
                    Назад
                </a>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="margin-top-5">Будинки</div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <button class="btn btn-primary pull-right"
                            data-toggle="modal"
                            data-target="#apartmentCreateModal">
                        Додати будинок
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th class="border-bottom-none">
                                    <span>Номер №</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var apartment in Model.Apartments.Where(x => x.Name != Consts.DefaultAddress))
                            {
                                <tr data-id="@apartment.Id">
                                    <td class="col-xs-12">
                                        <a href="@Url.Action("Details","Apartment", new {id = apartment.Id})">@apartment.Name</a>
                                        @if (apartment.CanDelete)
                                        {
                                            <i style="color: red; cursor: pointer"
                                               class="pull-right glyphicon glyphicon-trash"
                                               data-action="delete"
                                               data-item-id="@apartment.Id"></i>
                                        }
                                        <i style="color: gray; margin-right: 5px; cursor: pointer"
                                           class="pull-right glyphicon glyphicon-pencil"
                                           data-action="edit"
                                           data-item-id="@apartment.Id"
                                           data-street-id="@Model.Id"></i>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_ApartmentCreate", new ApartmentCreateModel { StreetId = Model.Id })
@Html.Partial("_ApartmentEdit")
@Html.Partial("_ConfirmDelete")
<script>
    $('[data-action="edit"]').click(function () {
        var apartment = $(this).parent().find("a")[0].text;
        var id = $(this).data('itemId');
        var streetId = $(this).data('streetId');
        $('#EditName').val(apartment);
        $('#EditId').val(id);
        $('#StreetId').val(streetId);
        $('#apartmentEditModal').modal('show');
    });

    $('[data-action="delete"]').click(function () {
        var id = $(this).data('item-id');
        $('#confirmDeleteModal').modal('show');
        $('#confirmDeleteModal')
            .find("#submitDelete")
            .data("item-id", id);
    });

    $("#submitDelete").click(function () {
        var id = $(this).data('itemId');
        $.get('@Url.Action("Delete","Apartment")', { id })
            .done(() => {
                var item = $(".table-striped > tbody").find("[data-id=" + id + "]");
                $(item).remove();
            });

        $('#confirmDeleteModal').modal('hide');

    });
</script>