Svbase/Svbase/Controllers/DistrictController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Enums;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class DistrictController : GeneralController
    {
        private readonly IDistrictService _districtService;


        public DistrictController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _districtService = ServiceManager.DistrictService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Index()
        {
            var model = _districtService.GetDistrictViewInitDataModel(DistrictType.Сonstituency);
            return View(model);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult List()
        {
            var items = _districtService.GetAllDistricts();
            return View(items);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(DistrictListModel model)
        {
            var result = _districtService.CreateDistrictBy(model);
            return result
                ? DistrictsBy(model.DistrictType)
                : RedirectToAction("Index");
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult DistrictsBy(DistrictType districtType)
        {
            var districts = _districtService.GetPanelBodyDistrictsBy(districtType);
            return PartialView("_DistrictsPanelBody", districts);
        }

        [HttpGet]
        public ActionResult DistrictsByType(DistrictType districtType)
        {
            return PartialView("_FilterMultiSelectPartial", _districtService.GetDistrictsByType(districtType).ToList());
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult StreetsBy(int cityId)
        {
            var streets = _districtService.GetPanelBodyStreetsBy(cityId);
            return PartialView("_DistrictsPanelBody", streets);

        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult ApartmentsBy(DistrictViewApartmentSearchFilter filter)
        {
            var apartments = _districtService.GetPanelBodyApartmentsBy(filter);
            return PartialView("_DistrictApartmentPanelBody", apartments);

        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Delete(DistrictListModel model)
        {
            var result = _districtService.DeleteById(model.Id);
            return result != null
                ? DistrictsBy(model.DistrictType)
                : RedirectToAction("Index");

        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult SaveDistrict(SaveDistrictModel model)
        {
            var result = _districtService.SaveDistrictBy(model);
            if (result)
            {
                return RedirectToAction("Index");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new { });

        }
    }
}

Svbase/Svbase/Controllers/StreetController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class StreetController : GeneralController
    {
        private readonly IStreetService _streetService;
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public StreetController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _streetService = ServiceManager.StreetService;
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(StreetCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City"); //Todo page not found
            }

            var newStreetItem = model.Update(new Street());
            var newApartmentItem = new Apartment { Name = Consts.DefaultAddress, Street = newStreetItem };
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _streetService.Add(newStreetItem);
            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            return RedirectToAction("Details", "City", new { id = model.CityId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(StreetCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var street = _streetService.FindById(model.Id);
            if (street == null)
            {
                return Json(new { status = "error" });
            }
            street.Name = model.Name;
            street.Pseudonym = model.Pseudonym;
            _streetService.Update(street);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var street = _streetService.GetStreetById(id);
            if (street == null)
            {
                RedirectToAction("List", "City");
            }
            return View(street);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _streetService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Views/District/Create.cshtml
@model Svbase.Core.Models.DistrictCreateModel
<div class="container body-content margin-top">

    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Id)
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Введіть назву вулиці", required = "required" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <span>Вулиці:</span>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            @for (var i = 0; i < Model.Streets.Count(); i++)
                            {
                                <div class="form-group">
                                    <div class="control-label col-xs-2">@Model.Streets[i].Name</div>
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.HiddenFor(model => model.Streets[i].Id)
                                            @Html.EditorFor(model => Model.Streets[i].IsChecked)
                                            @Html.ValidationMessageFor(model => Model.Streets[i].IsChecked, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-primary pull-right" type="submit">Зберегти</button>
                    <a class="pull-right" style="padding: 7px 12px;" href="@Url.Action("List")">Відмінити</a>
                </div>
            </div>
        </div>

    }
</div>

Svbase/Svbase/Views/District/Details.cshtml
@model Svbase.Core.Models.DistrictCreateModel
<div class="container body-content margin-top">

    @using (Html.BeginForm("Edit", "District"))
    {
        @Html.HiddenFor(model => model.Id)
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-xs-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Name", required = "required" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <span>Вибрані вулиці</span>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">

                            <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th class="col-xs-4">
                                            <span>Назва</span>
                                        </th>
                                        <th class="col-xs-12">
                                            <span>Місто</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var street in Model.Streets.Where(x => x.IsChecked))
                                    {
                                        <tr>
                                            <td class="col-xs-4">
                                                <a href="@Url.Action("Details","Street", new {id = street.Id})">@street.Name</a>
                                            </td>
                                            <td class="col-xs-12">
                                                <span>@street.CityName</span>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <span>Вулиці</span>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            @for (var i = 0; i < Model.Streets.Count(); i++)
                            {
                                <div class="form-group">
                                    <div class="control-label col-xs-2">@($"{Model.Streets[i].Name} ({Model.Streets[i].CityName})")</div>
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.HiddenFor(model => model.Streets[i].Id)
                                            @Html.EditorFor(model => Model.Streets[i].IsChecked)
                                            @Html.ValidationMessageFor(model => Model.Streets[i].IsChecked, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-primary pull-right" type="submit">Зберегти</button>
                    <a class="pull-right" style="padding: 7px 12px;" href="@Url.Action("List")">Відміна</a>
                </div>
            </div>
        </div>
    }
</div>

Svbase/Svbase/Views/District/Index.cshtml
@using Svbase.Core.Enums
@using Svbase.Core.Models
@model DistrictViewInitDataModel

<div class="body-content">
    <div class="row">
        <div class="container">
            <div id="district-alert-success" class="row" style="position: relative">
                <div class="alert alert-success district-alert display-none" style="font-weight: bold">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Збережено.
                </div>
            </div>
            <div id="district-alert-danger" class="row" style="position: relative">
                <div class="alert alert-danger district-alert display-none" style="font-weight: bold">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Виберіть округ і будинки.
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-header">Управління округами</h3>
                </div>
            </div>

            <div class="row padding-bottom-15">
                <div class="col-md-12 ignore-padding">
                    <div class="col-md-6">
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary  active"
                                   onclick="getDistrictsBy(@((int) DistrictType.Сonstituency))">
                                <input type="radio"
                                       name="options"
                                       id="constituency-districts"
                                       autocomplete="off"
                                       checked> Партійний
                            </label>
                            <label class="btn btn-secondary"
                                   onclick="getDistrictsBy(@((int) DistrictType.Custom))">
                                <input type="radio"
                                       name="options"
                                       id="custom-districts"
                                       autocomplete="off"> Виборчий
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-primary pull-right" onclick="saveDistrict()">
                            <a class="white-color">Зберегти</a>
                        </button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="col-sm-3 padding-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="font-weight: bold">
                                        Округи
                                        <i class="fa fa-plus-square fa-lg cursor-pointer"
                                           onclick="openCreateDistrictModal()"
                                           id="add-district-icon"
                                           style="color: #428bca; text-align: right; float: right"></i>
                                    </div>
                                    <div class="panel-body" id="districts-panel-body">
                                        @Html.Partial("_DistrictsPanelBody", @Model.Districts)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 padding-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="font-weight: bold">
                                        Населений пункт
                                        @*<i class="fa fa-plus-square fa-lg" style="color: #428bca; text-align: right; float: right"
                                            data-toggle="modal"
                                            data-target="#cityCreateModal"></i>*@
                                    </div>
                                    <div class="panel-body" id="cities-panel-body">
                                        @Html.Partial("_DistrictsPanelBody", @Model.Cities)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 padding-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="font-weight: bold">
                                        Вулиця
                                        @*<i class="fa fa-plus-square fa-lg" style="color: #428bca; text-align: right; float: right"
                                            data-toggle="modal"
                                            data-target="#streetCreateModal"></i>*@
                                    </div>
                                    <div class="scrollbar" style="max-height:420px;">
                                        <div class="panel-body" id="streets-panel-body">
                                            @Html.Partial("_DistrictsPanelBody", new List<DistrictPanelBodyItemModel>())
                                        </div>
                                    </div>
                                 </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 padding-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="font-weight: bold">
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <span class="pull-left">№ Буд</span>
                                                <input onclick="checkAllApartments()" class="pull-right" type="checkbox" id="all-apartments"/>
                                                <label class="pull-right cursor-pointer margin-right-xs" 
                                                       style="font-weight: normal"
                                                       for="all-apartments">Вибрати всі</label>
                                            </div>
                                        </div>
                                        @*<i class="fa fa-plus-square fa-lg" style="color: #428bca; text-align: right; float: right"
                                            data-toggle="modal"
                                            data-target="#apartmentCreateModal"></i>*@
                                    </div>
                                    <div class="scrollbar" style="max-height:415px;">
                                        <div class="panel-body" id="apartments-panel-body">
                                            @Html.Partial("_DistrictApartmentPanelBody", new List<DistrictPanelBodyApartmentModel>())
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*@Html.Partial("_BeneficiaryCreate", new BeneficiaryCreateModel())*@
@Html.Partial("_DistrictCreate", new DistrictListModel())
@*@Html.Partial("_CityCreate", new CityCreateModel())
    @Html.Partial("_ApartmentCreate", new ApartmentCreateModel())
    @Html.Partial("_FlatCreate", new FlatCreateModel())

    @Html.Partial("_StreetEdit")
    @Html.Partial("_ConfirmDelete")*@
<script>
    $(document).ready(() => {
        window.isDirty = false;
    });

    function getDistrictsBy(districtType) {
        var data = {
            DistrictType: districtType
        };
        $.get('@Url.Action("DistrictsBy","District")', data)
            .done((result) => {
                $("#districts-panel-body").html(result);
            });
    }

    function openCreateDistrictModal() {
        $('#districtCreateModal').modal('show');
    }

    function saveDistrict() {
        $('#loader').fadeIn();
        var activeDistrict = $("#districts-panel-body > .row.factor-item-active");
        var activeDistrictId = Number(activeDistrict.attr("data-item"));
        var activeStreet = $("#streets-panel-body > .row.factor-item-active");
        var activeStreetId = Number(activeStreet.attr("data-item"));
        var apartmentIds = getCheckedApartmentIds();
        var urlAction = "@Url.Action("SaveDistrict")";
        var model = {
            districtId: activeDistrictId,
            streetId: activeStreetId,
            apartmentIds: apartmentIds
        };

        $.ajax({
            url: urlAction,
            type: 'Post',
            data: { model: model },
            async: false
        }).done((data) => {
            showDistrictAlertSuccess();
            window.isDirty = false;
            $("#apartments-panel-body").html(null);
            var streetRows = $("#streets-panel-body > .row");
            streetRows.removeClass("factor-item-active");
            $('#loader').fadeOut();
        }).fail((resp) => {
            $('#loader').fadeOut();
            showDistrictAlertDanger();
        });
    }

    function showDistrictAlertSuccess() {
        if ($("#district-alert-success > div").hasClass("display-none")) {
            $("#district-alert-success > div").removeClass("display-none");
        }
        $("#district-alert-success").fadeIn("slow");
        window.setTimeout(function () {
            $("#district-alert-success").fadeOut("slow");
        }, 3000);
    }

    function showDistrictAlertDanger() {
        if ($("#district-alert-danger > div").hasClass("display-none")) {
            $("#district-alert-danger > div").removeClass("display-none");
        }

        $("#district-alert-danger").fadeIn("slow");
        window.setTimeout(function () {
            $("#district-alert-danger").fadeOut("slow");
        }, 3000);
    }

    function getCheckedApartmentIds() {
        var apartmentIds = [];
        $(".row.factor-item input:checked").each((index, element) => {
            if (!isNaN($(element).val())) {
                var id = Number($(element).val());
                apartmentIds.push(id);
            }
        });
        return apartmentIds;
    }


    function checkAllApartments() {
        var allApartments = $("#all-apartments");
        var isChecked = $(allApartments).prop("checked");
        var targets = $("#apartments-panel-body input");
        if (!targets || targets.length === 0) return;

        window.isDirty = true;
        if (!isChecked) {
            $(targets).prop("checked", false);
        } else {
            $(targets).prop("checked", true);
        }
    }

</script>

Svbase/Svbase/Views/District/List.cshtml
@using Svbase.Core.Enums
@using Svbase.Core.Models
@model IEnumerable<Svbase.Core.Models.DistrictListModel>

<div class="container body-content margin-top">
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-xs-8">
                    <h2 style="margin-top: 0">Округи</h2>
                </div>
                <div class="col-xs-4">
                    <a class="btn btn-primary pull-right"
                       data-toggle="modal"
                       data-target="#districtCreateModal" >
                        Додати округ
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th class="col-xs-6">
                                <span>Назва</span>
                            </th>
                            <th class="col-xs-6">
                                <span>Тип округа</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var district in Model)
                        {
                            <tr>
                                <td class="col-xs-6">
                                    <a href="@Url.Action("Details", new {id = district.Id})">@district.Name</a>
                                </td>
                                <td class="col-xs-6">
                                    @if (district.DistrictType == DistrictType.Сonstituency)
                                    {
                                        <span>Constituency</span>
                                    }
                                    @if (district.DistrictType == DistrictType.Custom)
                                    {
                                        <span>Custom</span>
                                    }
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@*@Html.Partial("_DistrictCreate", new DistrictCreateModel());*@