Svbase/Svbase/Controllers/ApartmentController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class ApartmentController : GeneralController
    {
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public ApartmentController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(ApartmentCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City");//Todo page not found
            }

            var newApartmentItem = model.Update(new Apartment());
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            return RedirectToAction("Details", "Street", new { id = model.StreetId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var apartment = _apartmentService.GetById(id);
            if (apartment == null)
            {
                RedirectToAction("List", "City");
            }
            return View(apartment);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(ApartmentCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var apartment = _apartmentService.FindById(model.Id);
            if (apartment == null)
            {
                return Json(new { status = "error" });
            }
            apartment.Name = model.Name;
            _apartmentService.Update(apartment);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _apartmentService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Controllers/FlatController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class FlatController : GeneralController
    {
        private readonly IFlatService _flatService;

        public FlatController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var flat = _flatService.GetById(id);
            if (flat == null)
            {
                RedirectToAction("List", "City");
            }
            return View(flat);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(FlatCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City"); //Todo page not found
            }

            var newFlatItem = model.Update(new Flat());
            _flatService.Add(newFlatItem);
            return RedirectToAction("Details", "Apartment", new { id = model.ApartmentId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(FlatCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var flat = _flatService.FindById(model.Id);
            if (flat == null)
            {
                return Json(new { status = "error" });
            }
            flat.Number = model.Name;
            _flatService.Update(flat);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _flatService.DeleteById(id);

            return Json(new { status = "success" });
        }

        [HttpGet]
        public ActionResult FindAddressByFlatId(int flatId)
        {
            var flatById = _flatService.FindById(flatId);
            BaseViewModel flat = new BaseViewModel
            {
                Id = flatById.Id,
                Name = flatById.Number
            };
            BaseViewModel apartment = new BaseViewModel
            {
                Id = flatById.ApartmentId,
                Name = flatById.Apartment.Name
            };
            BaseViewModel street = new BaseViewModel
            {
                Id = flatById.Apartment.StreetId,
                Name = flatById.Apartment.Street.Name
            };
            BaseViewModel city = new BaseViewModel
            {
                Id = flatById.Apartment.Street.CityId,
                Name = flatById.Apartment.Street.City.Name
            };

            return Json(new { flat, apartment, street, city }, JsonRequestBehavior.AllowGet);
        }

    }
}

Svbase/Svbase/Controllers/StreetController.cs
using Svbase.Controllers.Abstract;
using Svbase.Core.Consts;
using Svbase.Core.Data.Entities;
using Svbase.Core.Models;
using Svbase.Service.Factory;
using Svbase.Service.Interfaces;
using System.Web.Mvc;

namespace Svbase.Controllers
{
    public class StreetController : GeneralController
    {
        private readonly IStreetService _streetService;
        private readonly IApartmentService _apartmentService;
        private readonly IFlatService _flatService;

        public StreetController(IServiceManager serviceManager)
            : base(serviceManager)
        {
            _streetService = ServiceManager.StreetService;
            _apartmentService = ServiceManager.ApartmentService;
            _flatService = ServiceManager.FlatService;
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Create(StreetCreateModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("", @"Invalid Name");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", "City"); //Todo page not found
            }

            var newStreetItem = model.Update(new Street());
            var newApartmentItem = new Apartment { Name = Consts.DefaultAddress, Street = newStreetItem };
            var newFlatItem = new Flat { Number = Consts.DefaultAddress, Apartment = newApartmentItem };

            _streetService.Add(newStreetItem);
            _apartmentService.Add(newApartmentItem);
            _flatService.Add(newFlatItem);

            return RedirectToAction("Details", "City", new { id = model.CityId });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpPost]
        public ActionResult Edit(StreetCreateModel model)
        {
            if (model == null)
            {
                return Json(new { status = "error" });
            }

            var street = _streetService.FindById(model.Id);
            if (street == null)
            {
                return Json(new { status = "error" });
            }
            street.Name = model.Name;
            street.Pseudonym = model.Pseudonym;
            _streetService.Update(street);
            return Json(new { status = "success" });
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var street = _streetService.GetStreetById(id);
            if (street == null)
            {
                RedirectToAction("List", "City");
            }
            return View(street);
        }

        [Authorize(Roles = RoleConsts.Admin)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            _streetService.DeleteById(id);

            return Json(new { status = "success" });
        }
    }
}

Svbase/Svbase/Views/Apartment/Details.cshtml
@using Svbase.Core.Consts
@using Svbase.Core.Models
@model ApartmentViewModel
<div class="container body-content margin-top">
    <div class="row page-header">
        <div class="col-sm-12">
            <div class="col-md-6 col-xs-12">
                <h2 style="margin-top: 0">@Model.Name</h2>
            </div>
            <div class="col-md-6 col-xs-12">
                <a href="@Url.Action("Details", "Street", new {id = Model.StreetId})" class="pull-right padding-top-10">
                    Назад
                </a>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-6">
                    <div class="margin-top-5">Квартири</div>
                </div>
                <div class="col-xs-6">
                    <button class="btn btn-primary pull-right"
                            data-toggle="modal"
                            data-target="#flatCreateModal">
                        Додати квартиру
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th class="border-bottom-none">
                                    <span>Номер №</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var flat in Model.Flats.Where(x => x.Name != Consts.DefaultAddress))
                            {
                                <tr data-id="@flat.Id">
                                    <td class="col-xs-12">
                                        <a href="@Url.Action("Details","Flat", new {id = flat.Id})">@flat.Name</a>
                                        @if (flat.CanDelete)
                                        {
                                            <i style="color: red; cursor: pointer"
                                               class="pull-right glyphicon glyphicon-trash"
                                               data-action="delete"
                                               data-item-id="@flat.Id"></i>
                                        }
                                        <i style="color: gray; margin-right: 5px; cursor: pointer"
                                           class="pull-right glyphicon glyphicon-pencil"
                                           data-action="edit"
                                           data-item-id="@flat.Id"
                                           data-apartment-id="@Model.Id"></i>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_FlatCreate", new FlatCreateModel { ApartmentId = Model.Id })
@Html.Partial("_FlatEdit")
@Html.Partial("_ConfirmDelete")
<script>
    $('[data-action="edit"]').click(function () {
        var flat = $(this).parent().find("a")[0].text;
        var id = $(this).data('itemId');
        var apartmentId = $(this).data('apartmentId');
        $('#EditName').val(flat);
        $('#EditId').val(id);
        $('#ApartmentId').val(apartmentId);
        $('#flatEditModal').modal();
    });

    $('[data-action="delete"]').click(function () {
        var id = $(this).data('item-id');
        $('#confirmDeleteModal').modal('show');
        $('#confirmDeleteModal')
            .find("#submitDelete")
            .data("item-id", id);
    });

    $("#submitDelete").click(function () {
        var id = $(this).data('itemId');
        $.get('@Url.Action("Delete","Flat")', { id })
            .done(() => {
                var item = $(".table-striped > tbody").find("[data-id=" + id + "]");
                $(item).remove();
            });
        $('#confirmDeleteModal').modal('hide');

    });
</script>